import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Theme } from '@radix-ui/themes';

// Add the Geist font to the page and assign it to the CSS variable --font-geist-sans
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

//Add the Geist font to the page and assign it to the CSS variable --font-geist-mono
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

//metadata for the entire app (good for SEO) - each page can have its own
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// starting point - change only things in return statement
// children - will render different routes
// everything inside <html> but outside {children} will appear on every page
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
