import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import '@/styles/globals.css';
import { Container, Text, Theme } from '@radix-ui/themes';
import { ThemeProvider } from 'next-themes';
import { Navbar, SessionProviderWrapper } from '@/components/global';
import { ReactNode } from 'react';

// Add the Geist font to the page and assign it to the CSS variable --font-geist-sans
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
  preload: false, // Wyłącz automatyczny preload
});

//metadata for the entire app (good for SEO) - each page can have its own
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// starting point - change only things in return statement
// children - will render different routes
// everything inside <html> but outside {children} will appear on every page
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html
      lang="pl"
      suppressHydrationWarning
      className={`${geistSans.variable} antialiased`}
    >
      <body>
        <ThemeProvider attribute="class">
          <Theme>
            <SessionProviderWrapper>
              <div className="min-h-screen max-w-screen overflow-hidden grid grid-rows-[auto_1fr_auto]">
                <Navbar />
                <main className="[&_div.rt-Container]:h-full [&_div.rt-ContainerInner]:h-full">
                  <Container my="4" mx="2">
                    {children}
                  </Container>
                </main>
                <footer>
                  <Container py="4" mx="2" className="text-center">
                    <Text size="1">© 2025 Klaudia Błażyczek</Text>
                  </Container>
                </footer>
              </div>
            </SessionProviderWrapper>
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
