import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import '@/styles/globals.css';
import { Theme } from '@radix-ui/themes';
import { ThemeProvider } from 'next-themes';
import { SessionProviderWrapper } from '@/components/global';
import { ReactNode } from 'react';

// Add the Geist font to the page and assign it to the CSS variable --font-geist-sans
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
  preload: false, // Wyłącz automatyczny preload
});

//metadata for the entire app (good for SEO) - each page can have its own
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// starting point - change only things in return statement
// children - will render different routes
// everything inside <html> but outside {children} will appear on every page
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html
      lang="pl"
      suppressHydrationWarning
      className={`${geistSans.variable} antialiased`}
    >
      <body>
        <ThemeProvider attribute="class">
          <Theme>
            <SessionProviderWrapper>{children}</SessionProviderWrapper>
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
